project:
  type: website

website:
  title: "MTH_190"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: assignments.qmd
        text: Assignments
    
    sidebar:
    - id: Day_1
      title: "Day_1"
      style: "floating"
      collapse-level: 2
      align: left
      contents:
        - href: Day_1.qmd
        


format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

